### PR TITLE
Muffin_v2

### PR DESCRIPTION
**Pull request by Avanbelle**
Complete rework of MUFFIN_v1, 
This pull request includes several enhancements and updates to the Muffin workflow, aimed at improving performance, flexibility, and tool relevance. The key changes are as follows:

Code Review and Assembly Rewriting:
Imported and reviewed the existing Muffin project code to understand its structure and key functionalities.
Rewrote the assembly part of the code to enhance performance and efficiency.

Code Updates:
Reviewed and updated existing code and tools to ensure compatibility and effectiveness.

Input Read Management:
Added input read selection functionality, allowing processing of hybrid (short and long), short-only, or long-only data, and adapted processes accordingly.

Tool Integration and Removal:
Integrated new tools such as Chopper, QUAST, Samtools Merger, ComeBin, and SemiBin2.
Removed obsolete tools including Filtlong, Unicycler, MaxBin2, Merger, Concoct, and bin refinement tools to streamline the workflow.

### CODE REVIEW

**Comment by RVanDamme** [comment]
This is the merging of the work we did with Avanbelle on a fork, tasks are remaining but Muffin V2 is functional.
Task remaining, updating the README, updating all conda and containers to their latest version, testing the containers and updating the guide page.

**Comment by replikation** [comment]
Great to see improvements

**Comment by replikation** [comment]
Might want to look at the newest next flow release. They have some improvements in regards to easy tool version documentation for the user. And more for results and output channels.

https://nextflow.io/blog/2024/nextflow-2404-highlights.html

**Comment by RVanDamme** [comment]
Thanks! We will work on that.

**Pull request merged**
